version: "2.2"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=order
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=order
    volumes:
      - 'tempmee-order_db:/var/lib/mysql'
    networks:
      - tempmee-order-network
  redis:
    image: redis:5.0.5
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - './redis.conf:/etc/redis/redis.conf'
      - redis_data:/data
    networks:
      - tempmee-order-network

networks:
  tempmee-order-network:
volumes:
  tempmee-order_db:
  redis_data:
