## traefik.yml

# Docker configuration backend
log:
  level: DEBUG
api:
  insecure: true
  dashboard: true

providers:
  file:
    filename: /etc/traefik/routes.yml
entrypoints:
  web:
    address: ":80"


# API and dashboard configuration
api:
  insecure: true