package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"

	"github.com/bludot/tempmee/inventory/graph/generated"
	"github.com/bludot/tempmee/inventory/graph/model"
)

// FindBookByID is the resolver for the findBookByID field.
func (r *entityResolver) FindBookByID(ctx context.Context, id string) (*model.Book, error) {
	panic(fmt.Errorf("not implemented: FindBookByID - findBookByID"))
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
