// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bludot/tempmee/inventory/internal/services/jwt (interfaces: JWTServiceImpl)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_jwt_client.go -package=mocks github.com/bludot/tempmee/inventory/internal/services/jwt JWTServiceImpl
//
// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJWTServiceImpl is a mock of JWTServiceImpl interface.
type MockJWTServiceImpl struct {
	ctrl     *gomock.Controller
	recorder *MockJWTServiceImplMockRecorder
}

// MockJWTServiceImplMockRecorder is the mock recorder for MockJWTServiceImpl.
type MockJWTServiceImplMockRecorder struct {
	mock *MockJWTServiceImpl
}

// NewMockJWTServiceImpl creates a new mock instance.
func NewMockJWTServiceImpl(ctrl *gomock.Controller) *MockJWTServiceImpl {
	mock := &MockJWTServiceImpl{ctrl: ctrl}
	mock.recorder = &MockJWTServiceImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTServiceImpl) EXPECT() *MockJWTServiceImplMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockJWTServiceImpl) GenerateToken(arg0 string, arg1 map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockJWTServiceImplMockRecorder) GenerateToken(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockJWTServiceImpl)(nil).GenerateToken), arg0, arg1)
}

// ValidateToken mocks base method.
func (m *MockJWTServiceImpl) ValidateToken(arg0 string) (*map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", arg0)
	ret0, _ := ret[0].(*map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJWTServiceImplMockRecorder) ValidateToken(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTServiceImpl)(nil).ValidateToken), arg0)
}
