// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type APIInfo struct {
	UserAPI *UserAPI `json:"userApi"`
	Name    string   `json:"name"`
}

type RegisterInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (User) IsEntity() {}

type UserAPI struct {
	// Version of event publish service
	Version string `json:"version"`
}
