version: "2.2"
services:
  mysql:
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysecretpassword
      - MYSQL_DATABASE=user
    volumes:
      - 'tempme-user_db:/var/lib/mysql'
    networks:
      - tempme-user-network
  redis:
    image: redis:5.0.5
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - './redis.conf:/etc/redis/redis.conf'
      - redis_data:/data
    networks:
      - tempme-user-network

networks:
  tempme-user-network:
volumes:
  tempme-user_db:
  redis_data:
